version: '3'
services:

  eureka-serviceregistry:
    build: ./eureka
    ports:
      - "8761:8761"
    tty: true
    networks:
      - xml-net

  zuul:
    build: ./zuul
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    networks:
      - xml-net
    depends_on:
      - eureka-serviceregistry
      - ad-service
      - auth-service
      - message-service
      - rent-service

  database:
    image: mariadb:10.2
    container_name: database
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: xmldatabase
      MYSQL_USER: stipe
      MYSQL_PASSWORD: stipe123
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - xml-data:/var/lib/mysql
    networks:
      - xml-net

  ad-service:
    build: ./ad-service
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=database
    tty: true
    networks:
      - xml-net
    depends_on:
      - database
      - eureka-serviceregistry


  auth-service:
    build: ./auth-service
    ports:
      - "8082:8082"
    environment:
      - MYSQL_HOST=database
    tty: true
    networks:
      - xml-net
    depends_on:
      - database
      - eureka-serviceregistry

  message-service:
    build: ./message-service
    ports:
      - "8085:8085"
    environment:
      - MYSQL_HOST=database
    tty: true
    networks:
      - xml-net
    depends_on:
      - database
      - eureka-serviceregistry

  rent-service:
    build: ./rent-service
    ports:
      - "8084:8084"
    environment:
      - MYSQL_HOST=database
    tty: true
    networks:
      - xml-net
    depends_on:
      - database
      - eureka-serviceregistry

networks:
  xml-net:
volumes:
  xml-data:
